### ISSUE TITLE
插件无法正常加载

### ISSUE THREAD

**Issue by xuesenyaqwq** [SugarMGP/FestiveFirework#1]
#### 报错内容：
```
[07:46:52 ERROR]: Error occurred while enabling FestiveFirework v1.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "this.timerFile" is null
        at io.github.sugarmgp.festivefirework.TimerManager.saveDefaultConfig(TimerManager.java:122) ~[FestiveFirework-1.2.0 (1).jar:?]
        at io.github.sugarmgp.festivefirework.TimerManager.<init>(TimerManager.java:28) ~[FestiveFirework-1.2.0 (1).jar:?]
        at io.github.sugarmgp.festivefirework.FestiveFirework.onEnable(FestiveFirework.java:11) ~[FestiveFirework-1.2.0 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by xuesenyaqwq** [comment]
放入插件文件夹内只生成了一个空的config文件
